AWSTemplateFormatVersion: '2010-09-09'
Description: Podatny S3 Bucket i Polityka IAM
Resources:
  MyDatabase:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: ecommerce_db
      Engine: mysql
      MasterUsername: admin
      MasterUserPassword: Password123!
      AllocatedStorage: '20'
      DBInstanceClass: db.t3.micro
      PubliclyAccessible: true
      StorageEncrypted: false
