AWSTemplateFormatVersion: '2010-09-09'
Description: Insecure Modern Architecture No ACLs version
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
  InsecureSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow all
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0
  DataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub corporate-data-${AWS::AccountId}
  DataBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref DataBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: 'PublicReadWrite'
            Effect: 'Allow'
            Principal: '*'
            Action: 
              - 's3:GetObject'
              - 's3:PutObject'
            Resource: !Sub 'arn:aws:s3:::${DataBucket}/*'
  ServerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: 'DangerousPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action: 'iam:*'
                Resource: '*'
  AppInstance:
    Type: AWS::EC2::Instance
    Properties:
      IamInstanceProfile: !Ref ServerInstanceProfile
      InstanceType: t3.small
      ImageId: ami-0ea87431b78a82070
      SecurityGroupIds: 
        - !Ref InsecureSG
      SubnetId: !Ref PublicSubnet
      MetadataOptions:
        HttpTokens: optional
  Database:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: '20'
      DBInstanceClass: db.t3.micro
      Engine: postgres
      MasterUsername: dbadmin
      MasterUserPassword: HardcodedPassword123
      PubliclyAccessible: true
      StorageEncrypted: false
  NotificationQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: orders-queue
  QueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref NotificationQueue
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: sqs:*
  ServerInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles: [ !Ref ServerRole ]